name: zip and upload

on:
  push:
    branches:
      - main
jobs:
  zip:
    container:
      image: node:alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run zip
      - uses: actions/upload-artifact@v2
        with:
          name: vno16
          path: vno16.zip

